apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: app
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    root: # database owner
      - superuser
      - createdb
  databases:
    mcmicroservices: root # dbname: owner
  postgresql:
    version: "14"
