apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: order-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 838107339577.dkr.ecr.ap-south-1.amazonaws.com/w-k-s/mcmicroservices/order-service:714b263e7a1739ab1ad539745558afa9a8c98f94
          imagePullPolicy: Always
          env:
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CONFIG_SERVER_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://acid-minimal-cluster.app.svc.cluster.local:5432/mcmicroservices
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.app.svc.cluster.local:9091,kafka-cluster-kafka-bootstrap.app.svc.cluster.local:9092,kafka-cluster-kafka-bootstrap.app.svc.cluster.local:9093
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.app.svc.cluster.local:9091,kafka-cluster-kafka-bootstrap.app.svc.cluster.local:9092,kafka-cluster-kafka-bootstrap.app.svc.cluster.local:9093
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
